spring:
  datasource:
    url: jdbc:mysql//localhost:3306/springjpa?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: org.msql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true